# Generated by Django 2.1.7 on 2019-03-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190306_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bedtooms',
            new_name='bedrooms',
        ),
    ]
